package exceldatadriven;

public class EmpDataClass {

	String[] firstnames = {"priya", "Tanya", "Priyanka", "divya", "tanvi", "Ishita", "vani", "Anjali", "Shreya", "riya", "Sneha", "Aishwarya", "Gayatri", "varsha", "Ira", "sanjana", "Niharika", "Nikita", "natasha", "Neha", "shivangi", "ramya", "Isha", "ananya", "shivani", "Sakshi", "Aswini", "Suhani", "leah", "Pavithra", "seema", "Anusha", "simran", "nishi", "Anushri", "Ayushi", "Radhika", "tanu", "krithika", "Anisha", "Akansha", "Sadaf", "Nishita", "diya", "Siya", "Abigail", "Kalyani", "Rishita", "Aastha", "Mary", "sara", "prachi", "indhumathi", "shrinidhi", "Papuii colney", "rhea", "Katherine", "Rutuja", "arti", "debbie", "Crowny", "manisha", "Mahima", "Aditi", "Aashna", "Tisha", "moii chhangte", "Sam", "swati", "dia", "ria", "anu", "Neelam", "N.Priyanka", "NISHA", "Chandralekha", "Mitali", "Dawn", "Dilmini", "kamalika", "Khushi",  "Anjana", "Arya", "deepa", "juvina", "Angel", "anamika", "Lavanya", "ishika", "Lily", "Archita", "Rashi", "sarah", "sasashy", "vaishnavi", "diksha", "Arusha", "Niti", "vidhya", "kavya", "rahul", 
			"Abhishek", "Aditya", "Amit", "mahesh", "ROHIT", "yash", "Ankit", "shyam", "Deepak", "Aryan", "Raj", "Arjun", "Manoj", "ankur", "akash", "Karan", "rakesh", "Sam", "Naveen", "Ashish", "Vinay", "Parth", "Mayank", "vivek", "Aaditya", "Neeraj", "kumar", "Abhinav", "Soham", "Pranav", "Rohan", "ajith", "ABHI", "PRATEEK", "Raghav", "Rishabh", "Vaibhav", "jay", "Kunal", "vishal", "vikas", "Raju", "sanjay", "manish", "shivam", "Nishant", "Nitin", "Krishna", "krish", "john", "Anil", "prince", "Varun", "Anish", "ALOK", "abdul", "SUNNY", "Siddharth", "vedant", "manu", "MOHIT", "Arun", "Ajay", "Shashank", "Dhruv", "Anirudh", "Ram", "sanchit", "gokul", "Anubhav", "Sumit", "Deepro", "Shekhar", "Anurag", "Akshay", "Paaus", "shaan", "Nikhil", "Kartik", "GIRISH", "SHAIL", "Prashant", "Sunil", "Pratik", "Deep", "Ramanan", "Aniket", "Jatin", "dinesh", "pawan", "Rajeev", "atul", "mayur", "tushar", "Harish", "Avinash", "Avi", "SURESH", "Ajeet"};
	
	String[] companynames = {"Harini Informatics", "RajuTech", "Inovies Conculting Pvt Ltd", "Eclature Technologies", "SB Technologies", "Sanoits Software Solutions Pvt Ltd", "Erudite Soft Private Ltd", "Techsoware Pvt Ltd", "Avishkar Abovo Software Solutions", "N4 Express", "Concert Tech Corporation", "VeServ", "PiLog India Private Limited", "V S Soft Tech", "Kensium Solutions Pvt Ltd", "Hi Caliber IT Solutions", "Brio Technologies Private Limited", "Team Embedded", "Info Edge Solutions", "Zolon Tech Ltd", "Roads Software Corporation", "Nihar Solutions", "I2Space Technologies", "C4i Technologies", "Beehyv Software", "Sahithi Systems Pvt Ltd", "Mind Thread Information Technology Pvt Ltd", "Bipsum Software Soultions Pvt Ltd", "New Horizon Cybersoft Ltd", "Avighna IT Solutions", "Phonologies", "Serveen Software Systems ( P) Ltd", "Suvisan Info Technologies (p) Ltd", "Eureka Technocrats Pvt Ltd", "Sreeven Infocom Limited", "Nihar Info Global Limited", "Systel", "Yardstick Computer Service", "Geospatial Informatics Pvt Ltd", 
			"Fiables IT Outsourcing Services", "Conrep Solutions Pvt Ltd", "Four Soft Ltd", "Mani Software Solutions", "Quark Tech", "OGS", "Vasavi Prosoft Transcription Ltd", "TSS India Pvt Ltd", "Callippus Solutions Pvt Ltd", "Avon Technologies", "ISS", "Warangal Technologies (P) Limited", "Innopark (India) Pvt Ltd", "Choice Solutions Ltd", "Tarkshya", "Veeras Infotek", "WebTek Labs", "Externetworks", "Framework-sdc", "M&M Software Solutions", "Peritus Info Tech", "Spark Solutions Pvt Ltd", "Spectramind Solutions", "G Tech", "Netindia Pvt Ltd", "Pramati Technologies", "Etisbew Technology Group", "Prathina Net Entertainment Ltd", "MM IT Company", "Hard&Soft Computings Pvt Ltd", "Vensoft India Pvt Ltd", "CHIITTI DIGISOFTECH PVT. LTD.", "Carbynetech", "Myneni's IT Solutions", "Infasta Soft Solutions Pvt. Ltd", "Beehyv Software", "Sahithi Systems Pvt Ltd", "Mind Thread Information Technology Pvt Ltd", "Bipsum Software Soultions Pvt Ltd", 
			"New Horizon Cybersoft Ltd", "Avighna IT Solutions",  "Phonologies", "Serveen Software Systems ( P) Ltd", "Suvisan Info Technologies (p) Ltd", "Eureka Technocrats Pvt Ltd", "Sreeven Infocom Limited", "Nihar Info Global Limited", "Systel", "Yardstick Computer Services", "Geospatial Informatics Pvt Ltd", "Fiables IT Outsourcing Services", "Conrep Solutions Pvt Ltd", "Four Soft Ltd", "Mani Software Solutions", "Quark Tech", "OGS", "Vasavi Prosoft Transcription Ltd", "TSS India Pvt Ltd", "Callippus Solutions Pvt Ltd", "Avon Technologies", "ISS", "Clematis Technology Solutions Pvt Ltd", "AIT SOLUTIONS", "Two Power N Technologies Pvt. Ltd", "SmartMobile Technologies", "NCPL", "Yoddha Software Solutions", "Erudite Infotech", "IBrand Solutions", "Ed Ventures E-Learning Pvt Ltd", "Cravaka Info Systems", "Visisht Info Solutions Pvt Ltd", "Young India Information Technology Services (P) Lt", "HungryBird Resources", "Swetha Solutions", "Begonia Information Systems", "TIPS Consulting Solutions", 
			"Incresol Software Services Private Limited", "Intelex Systems", "Metanoia Software Solutions P Ltd", "Maisa Solutions", "Vignesh IT Solutions", "Advanced Networks", "Hiperio Systems", "WINIT Software Pvt Ltd"};

	String[] lastnames = {"Acharya", "Agarwal", "Agate", "Aggarwal", "Agrawal", "Ahluwalia", "Ahuja", "Amble", "Anand", "Andra", "Anne", "Apte", "Arora", "Arya", "Atwal", "Aurora", "Babu", "Badal", "Badami", "Bahl", "Bahri", "Bail", "Bains", "Bajaj", "Bajwa", "Bakshi", "Bal", "Bala", "Bala", "Balakrishnan",  "Balan", "Balasubramanian", "Balay", "Bali", "Bandi", "Banerjee", "Banik", "Bansal", "Barad", "Barad", "Baral", "Baria", "Barman", "Basak", "Bassi", "Basu", "Bath", "Batra", "Batta", "Bava", "Bawa", "Bedi", "Behl", "Ben", "Bera", "Bhagat", "Bhakta", "Bhalla", "Bhandari", "Bhardwaj", "Bhargava", "Bhasin", "Bhat", "Bhatia", "Bhatnagar", "Bhatt", "Bhattacharyya", "Bhatti", "Bhavsar", "Bir", "Biswas", "Boase", "Bobal", "Bora", "Bora", "Borah", "Borde", "Borra", "Bose", "Brahmbhatt", "Brar", "Buch", "Buch", "Bumb", "Butala", "Chacko", "Chad", "Chada", "Chadha", "Chahal", "Chakrabarti", "Chakraborty", "Chana", "Chand", "Chanda", "Chander", "Chandra", "Chandran", "Char", "Chatterjee"};
}
